services:
  aurorabeacon:
    build: .
    container_name: aurorabeacon
    restart: always
    ports:
      - "47291:8000"
    volumes:
      - aurorabeacon_data:/app/data
volumes:
  aurorabeacon_data:
    external: false