[project]
name = "aurorabeacon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dyslexic Dogo", email = "88225949+dyslexicdogo@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.3",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
aurorabeacon = "aurorabeacon:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
